### ISSUE TITLE
The pressure page when expanded doesn't work properly

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#123]
## Bug Description
The pressure page when expand doesn't work properly

### Steps to Reproduce
1. Click on 'pressure'
2. See error

### Expected Behavior
It will show the line of pressure.

### Actual Behavior
It doesn't show the line

### Screenshots
My phone has an error when I am trying to insert the image into github. I will post when I am on PC.

### Environment
- OS: Android 12
- App version: 1.7.9
- Device: Xiaomi Redmi 9T
- Browser (if applicable): Chrome

**Comment by PranshulGG** [comment]
Yeah, I’ve noticed that too—sometimes the pressure bar is empty. It’ll be fixed in the next version.

**Comment by Tuan1-2-3** [comment]
It's working fine now, but two hours ago, it was still having issues.

**Comment by PranshulGG** [comment]
What was the pressure value when you noticed the error?

**Comment by Tuan1-2-3** [comment]
It is 1009.5 hPa, at 5.59 a.m.
